version: '3.3'

services:
  base-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - base-app-db
    image: tubess:8.0-apache
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
  base-app-db:
    container_name: db
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: doraemon123
        MYSQL_DATABASE: sample_db
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin123
    volumes:
        - ./Database/sample_db.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
        - "9906:3306"

  base-app-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8008:80'
    restart: always
    environment:
        PMA_HOST: db
        UPLOAD_IMAGE : 300M
    depends_on:
        - base-app-db